export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const PASSWORD_RESET_FAIL = 'PASSWORD_RESET_FAIL';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const PASSWORD_RESET_CONFIRM_FAIL = 'PASSWORD_RESET_CONFIRM_FAIL';
export const PASSWORD_RESET_CONFIRM_SUCCESS = 'PASSWORD_RESET_CONFIRM_SUCCESS';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
export const ACTIVATION_FAIL = 'ACTIVATION_FAIL';
export const GOOGLE_AUTH_SUCCESS = 'GOOGLE_AUTH_SUCCESS';
export const GOOGLE_AUTH_FAIL = 'GOOGLE_AUTH_FAIL';
export const FACEBOOK_AUTH_SUCCESS = 'FACEBOOK_AUTH_SUCCESS';
export const FACEBOOK_AUTH_FAIL = 'FACEBOOK_AUTH_FAIL';
export const LOGOUT = 'LOGOUT';


// <-- cart -->
export const CART = 'CHANGE_CART';
export const SHOW_CART = 'SHOW_CART';
export const ADD_ITEM = 'ADD_ITEM_TO_CART';
export const CHECKOUT = 'VIEW_CHCKOUT';
export const USER_STORES = 'UPDATE_USER_STORES';



// <--local storage-->
export const LOC_ADD_ITEM = "ADD_ITEM_TO_CART"
export const LOC_DEL_ITEM = "DEL_ITEM_FROM_CART"
// export const LOC_ADD_ITEM = "ADD_ITEM_TO_CART"
// export const LOC_ADD_ITEM = "ADD_ITEM_TO_CART"
// export const LOC_ADD_ITEM = "ADD_ITEM_TO_CART"
// export const LOC_ADD_ITEM = "ADD_ITEM_TO_CART"




//<--user dashboard-->
export const ALL_ORDERS = "GET_ALL_ORDERS";
export const OPEN_ORDERS = "GET_OPEN_ORDERS";